### ISSUE TITLE
Need Help with a Compressed Dataset Update

### ISSUE THREAD

**Issue by lynette-1** [SOM-Research/HFCommunity#15]
❓ Ask us anything
Hi！I have noticed that there have been recent updates to the extractor tool. However, due to limitations in my computer's hardware, I am unable to run the code effectively to generate the updated dataset. Would it be possible for you to share a compressed dataset for version 1.1 on HFcommunity?  Thanks!
(Write your answer here.)

**Comment by ademait** [comment]
Hi @lynette-1 ! The version 1.1 is on its way. 🚀  It is expected to be released this month.

**Comment by ademait** [comment]
Closing the thread. For further questions open a new issue 😊
